
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: 1234
#  devtools:
#    livereload:
#      enabled: true
  jwt:
    secret: testJWT
#  file:
#     location: /home/ubuntu/uploads
#  servlet:
#    multipart:
#      max-file-size: 512MB
#      max-request-size: 512MB
#  mail:
#     host: smtp.gmail.com
#     port: 465
#     username: "i3a101.devit.io@gmail.com"
#     password: "dntnvmfhwprxm!@"
#     properties:
#        mail.smtp.auth: true
#        mail.smtp.ssl.enable: true
#        mail.smtp.ssl.trust: smtp.gmail.com
#        mail.smtp.starttls.enable: false
        
    
mybatis:
  type-aliases-package: com.ssafy.catchcam.model
  mapper-locations: classpath:mappers/**/*.xml
server:
  port: 8080